### ISSUE TITLE
install_executables does not seem to work on OSX 

### ISSUE THREAD

**Issue by ehinderer** [rmflight/categoryCompare2#27]
Running install_executables(path="/usr/bin") does not give any errors, but does not move the executables into the path specified. I've also tried running the scripts directly from the library, but the shebang doesn't point to the correct Rscript location on my system.

**Comment by rmflight** [comment]
closed by 906721f

Turns out I was grabbing the wrong directory. Also, it seems that R should be marking them as executable upon install of the package, so that shouldn't be an issue, so removed that bit of code.
