### ISSUE TITLE
Problem with export(label_go_communities) in NAMESPACE

### ISSUE THREAD

**Issue by jmmitc06** [rmflight/categoryCompare2#28]
Installing categoryCompare2 fails yielding "undefined exports: label_go_communities". The issue can be bypassed by commenting out export(label_go_communities) in NAMESPACE* line 42 with no obvious ill effects. 

On Windows 10, x86_64-w64-mingw32 running R version 3.6.2 (2019-12-12).

**Comment by rmflight** [comment]
Thanks Josh! Yeah, I had removed that function, but hadn't updated and pushed the changes to the documentation.
